SET MODE MSSQLServer;

CREATE SCHEMA Users;
CREATE SCHEMA Calculate;


CREATE TABLE Users.Main(
	Id BIGINT IDENTITY(1,1) NOT NULL,
	Login NVARCHAR(100) NULL,
	Password NVARCHAR(20) NULL,
	BirthDay DATE NULL,
	NickName NVARCHAR(25) NULL,
    PRIMARY KEY (Id)
);

CREATE TABLE Calculate.Equations(
	Id BIGINT IDENTITY(1,1) NOT NULL,
	FirstNumber BIGINT NOT NULL,
	SecondNumber BIGINT NOT NULL,
	Type NVARCHAR(10) NOT NULL,
    PRIMARY KEY (Id)
);

CREATE TABLE Calculate.UsersResult(
	Id BIGINT IDENTITY(1,1) NOT NULL,
	UserId BIGINT NULL,
	EquationId BIGINT NULL,
	Success BIT NULL,
	Session UNIQUEIDENTIFIER NULL,
	ResultDateStamp DATETIME2(7) NULL,
    PRIMARY KEY (Id)
);


CREATE TABLE Calculate.UsersScore(
	Id BIGINT IDENTITY(1,1) NOT NULL,
	UserId BIGINT NOT NULL,
	Time BIGINT NOT NULL,
	Session UNIQUEIDENTIFIER NOT NULL,
	Score BIGINT NOT NULL,
	ResultDateStamp DATETIME NULL,
    PRIMARY KEY (Id)
);